#!/usr/bin/env node

const express = require('express');

const httpErrors = require('http-errors');

const app = express();

app.use('/slack', require('./slack'));

app.use(function(req, res, next) {
  next(httpErrors(404));
});

app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.send(err.message);
});

module.exports = app;
